### ISSUE TITLE
Download-sheet fails if investigation path returned by SODAR is not archive root

### ISSUE THREAD

**Issue by mikkonie** [bihealth/cubi-tk#111]
**Describe the bug**

SODAR maintains the original directory structure of imported sample sheets, as some people expect archived ISA-Tab sheets to be contained within a directory inside the zip while others may not. 

Similarly, if `i_dir_name` is set in the cubi-tk templates, SODAR preserves this in its database and returns the investigation path accordingly.

It seems that if the investigation path is returned by SODAR and  `download-sheet` creates a new archive from the JSON data, it results in investigation, study and assay files being inserted in different directories. This creates a crash.

I'm adding a dump of this crash in issue comments.

**To Reproduce**

1. Create or import a sample sheet in SODAR which places ISA-Tab files within a directory in an archive.
2. Run `download-sheet`

*Disclaimer:* I've only had time to look into this superficially, so I'm not 100% percent this is all that's needed for reproduction. Feel free to comment if you feel something is missing.

**Expected behavior**

The investigation, study and assay files should all be placed in the same directory within the created archive, or in the archive root.

**Additional context**

It is also possible that the data returned by SODAR describing the path is somehow misleading and I'm up for suggestions for future improvements. However, this part of the SODAR API has not been touched in a long time, so for now I'm considering it to be working as expected.

**Comment by mikkonie** [comment]
Log of crash with potentially sensitive information redacted:

```
[I 220714 11:43:20] Starting cubi-tk sodar download-sheet
[I 220714 11:43:20]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, makedirs=True, overwrite=False, dry_run=False, yes=False, show_diff=False, show_diff_side_by_side=False, project_uuid='xxx', output_dir='.')
[I 220714 11:43:20] Writing DIRECTORY-IN-ARCHIVE/i_Investigation.txt
[I 220714 11:43:20] About to write file contents to DIRECTORY-IN-ARCHIVE/i_Investigation.txt
Is this OK? [yN] y
Traceback (most recent call last):
  File "/data/gpfs-1/projects/medgen_namse/work/miniconda3.user_xxx/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/user_xxx/development/cubi-tk/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/user_xxx/development/cubi-tk/cubi_tk/sodar/__init__.py", line 93, in run
    return args.sodar_cmd(args, parser, subparser)
  File "/fast/work/users/user_xxx/development/cubi-tk/cubi_tk/sodar/download_sheet.py", line 107, in run
    return cls(Config(**args)).execute()
  File "/fast/work/users/user_xxx/development/cubi-tk/cubi_tk/sodar/download_sheet.py", line 134, in execute
    self._write_file(
  File "/fast/work/users/user_xxx/development/cubi-tk/cubi_tk/sodar/download_sheet.py", line 157, in _write_file
    overwrite_helper(
  File "/fast/work/users/user_xxx/development/cubi-tk/cubi_tk/common.py", line 254, in overwrite_helper
    with out_path_obj.open("wt") as output_file:
  File "/data/gpfs-1/projects/medgen_namse/work/miniconda3.user_xxx/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/data/gpfs-1/projects/medgen_namse/work/miniconda3.user_xxx/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'DIRECTORY-IN-ARCHIVE/i_Investigation.txt'
```
