### ISSUE TITLE
cubi-tk sodar download-sheet fails

### ISSUE THREAD

**Issue by january3** [bihealth/cubi-tk#52]
**Describe the bug**
When I attempt to download the ISATAB sheet, I get an obscure Python error:

```
[I 210630 01:13:26] Starting cubi-tk sodar download-sheet
[I 210630 01:13:26]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, makedirs=True, overwrite=False, dry_run=
False, yes=False, show_diff=False, show_diff_side_by_side=False, project_uuid='1e526322-50b8-47dd-a419-759d03d19a0b', output_dir='isatab')
Traceback (most recent call last):
  File "/fast/users/jweiner_m/work/miniconda3/envs/cubi-tk/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/__main__.py", line 119, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/sodar/__init__.py", line 93, in run
    return args.sodar_cmd(args, parser, subparser)
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/sodar/download_sheet.py", line 107, in run
    return cls(Config(**args)).execute()
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/sodar/download_sheet.py", line 135, in execute
    out_path, isa_dict["investigation"]["path"], isa_dict["investigation"]["tsv"]
TypeError: 'Investigation' object is not subscriptable
```

**To Reproduce**
Run `cubi-tk sodar download-sheet 1e526322-50b8-47dd-a419-759d03d19a0b isatab`

**Expected behavior**
I expected a concise message explaining what went wrong. Either that, or cubi-tk actually downloading the isa-tab.

**Additional context**
There may be a problem with the isatab for this project. This is a sea-snap project btw.

**Comment by holtgrewe** [comment]
That's a classic Python exception trace a and a bug.

**Comment by eudesbarbosa** [comment]
**Code**
sodar-cli: [L96](https://github.com/bihealth/sodar-cli/blob/main/sodar_cli/api/models.py#L96)
snappy-pipeline: [L128](https://github.com/bihealth/cubi-tk/blob/master/cubi_tk/sodar/download_sheet.py#L128)

Possible solution:
```
128         investigation = api.samplesheet.retrieve(
129             sodar_url=self.config.sodar_url,
130             sodar_api_token=self.config.sodar_api_token,
131             project_uuid=self.config.project_uuid,
132         )
133         try: # Investigation has no file - commented out
134             # self._write_file(
135             #     out_path, isa_dict.irods_path, isa_dict["investigation"]["tsv"]
136             # )
137             for study in investigation.studies.values():
138                 self._write_file(out_path, study.file_name, get_content_tsv(study.irods_path, study.file_name))
139             for assay in investigation.assays.values():
140                 self._write_file(out_path, assay.file_name, get_content_tsv(assay.irods_path, assay.file_name))
```

@holtgrewe, is there an easier way to get the content from studies and assays, other than additional downloads from iRODS? And how to solve this for investigation (no iRODS path)?
