### ISSUE TITLE
cubi-tk  sodar pull-raw-data fails with a cryptic message

### ISSUE THREAD

**Issue by january3** [bihealth/cubi-tk#53]
**Describe the bug**

Downloading raw data from a project with `cubi-tk sodar pull-raw-data` results in a cryptic error message. 

(cubi-tk) [jweiner_m@med0115 import_from_SODAR]$ cubi-tk sodar pull-raw-data 1e526322-50b8-47dd-a419-759d03d19a0b fastq
[I 210630 01:22:22] Starting cubi-tk sodar pull-raw-data
[I 210630 01:22:22]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, overwrite=False, min_batch=0, dry_run=False, irsync_threads=None, yes=False, project_uuid='1e526322-50b8-47dd-a419-759d03d19a0b', assay=None, output_dir='fastq')
Traceback (most recent call last):
  File "/fast/users/jweiner_m/work/miniconda3/envs/cubi-tk/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/__main__.py", line 119, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/sodar/__init__.py", line 93, in run
    return args.sodar_cmd(args, parser, subparser)
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/sodar/pull_raw_data.py", line 137, in run
    return cls(Config(**args)).execute()
  File "/fast/work/users/jweiner_m/Projects/Software/cubi-tk/cubi_tk/sodar/pull_raw_data.py", line 158, in execute
    investigation = api.investigations.get(
AttributeError: module 'sodar_cli.api' has no attribute 'investigations'

**To Reproduce**
see above

**Expected behavior**
A clear and concise error message stating what the problem is. Or downloading the raw data correctly.

**Additional context**
Again, this is a sea-snap project.

**Comment by holtgrewe** [comment]
This is a bug with non-adjusted API calls after cutting out sodar-cli, I believe.

**Comment by eudesbarbosa** [comment]
Solved in #49
