### ISSUE TITLE
Upload `ngs-mapping` step to multiple assays projects impossible

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/cubi-tk#68]
**Incomplete support of multiple assays in `cubi-tk snappy itransfer-ngs-mapping`**
The upload to SODAR of the output of `snappy`'s `ngs-mapping` step appears to fail for projects with multiple assays. I have tried:

- Using the landing zone UUID as destination:
```
[I 211004 11:40:54] Starting cubi-tk snappy itransfer-ngs-mapping
[I 211004 11:40:54]   args: Namespace(base_path='/fast/work/groups/cubi/projects/2021-06-25_Lung_Patients_WGS/pipeline', cmd='snappy', config=None, destination='91044dc1-48bc-49a1-ba10-ed9487d97ff4', first_batch=0, last_batch=None, mapper='bwa', num_parallel_transfers=8, remote_dir_date='2021-09-30', remote_dir_pattern='{library_name}/ngs_mapping/{date}', snappy_cmd=<bound method SnappyItransferCommandBase.run of <class 'cubi_tk.snappy.itransfer_ngs_mapping.SnappyItransferNgsMappingCommand'>>, sodar_api_token='37fca4c405664d8e298e7895c4726051b0772a825c656f8d641bb02e77f33502', sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', tsv_shortcut='cancer', validate_and_move=False, verbose=False, yes=False)
[I 211004 11:40:54] Will start at /fast/work/groups/cubi/projects/2021-06-25_Lung_Patients_WGS/pipeline
Traceback (most recent call last):
  File "/fast/work/users/blance_c/miniconda3/envs/sak/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/__init__.py", line 89, in run
    return args.snappy_cmd(args, parser, subparser)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 194, in run
    return cls(args).execute()
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 636, in execute
    start_path=self.args.base_path, uuid=self.args.destination
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/common.py", line 116, in get_biomedsheet_path
    raise CouldNotFindBioMedSheet(msg)
cubi_tk.snappy.common.CouldNotFindBioMedSheet: Could not find sample sheet for UUID 91044dc1-48bc-49a1-ba10-ed9487d97ff4. Dataset configuration: All = {'sodar_uuid': '3cdefbd9-67b1-465e-937a-232ec1da47f8', 'file': 'Samplesheet.tsv', 'search_patterns': [{'left': '**/*_R1_001.fastq.gz', 'right': '**/*_R2_001.fastq.gz'}], 'search_paths': ['/fast/scratch/groups/cubi/blance_c/2021-06-25_Lung_Patients_WGS/incoming'], 'type': 'matched_cancer', 'naming_scheme': 'only_secondary_id'}
```
- Using the landing zone SODAR path as destination:
```
(sak) [blance_c@med0624 pipeline]$ cubi-tk snappy itransfer-ngs-mapping --tsv-shortcut cancer --remote-dir-date 2021-09-30 /sodarZone/projects/3c/3cdefbd9-67b1-465e-937a-232ec1da47f8/landing_zones/blance@CHARITE/single_cell_lung_patients/lung_patients_whole_genome_sequencing/20210924_201211
[I 211004 11:42:21] Starting cubi-tk snappy itransfer-ngs-mapping
[I 211004 11:42:21]   args: Namespace(base_path='/fast/work/groups/cubi/projects/2021-06-25_Lung_Patients_WGS/pipeline', cmd='snappy', config=None, destination='/sodarZone/projects/3c/3cdefbd9-67b1-465e-937a-232ec1da47f8/landing_zones/blance@CHARITE/single_cell_lung_patients/lung_patients_whole_genome_sequencing/20210924_201211', first_batch=0, last_batch=None, mapper='bwa', num_parallel_transfers=8, remote_dir_date='2021-09-30', remote_dir_pattern='{library_name}/ngs_mapping/{date}', snappy_cmd=<bound method SnappyItransferCommandBase.run of <class 'cubi_tk.snappy.itransfer_ngs_mapping.SnappyItransferNgsMappingCommand'>>, sodar_api_token='37fca4c405664d8e298e7895c4726051b0772a825c656f8d641bb02e77f33502', sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', tsv_shortcut='cancer', validate_and_move=False, verbose=False, yes=False)
[I 211004 11:42:21] Will start at /fast/work/groups/cubi/projects/2021-06-25_Lung_Patients_WGS/pipeline
Traceback (most recent call last):
  File "/fast/work/users/blance_c/miniconda3/envs/sak/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/__init__.py", line 89, in run
    return args.snappy_cmd(args, parser, subparser)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 194, in run
    return cls(args).execute()
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 636, in execute
    start_path=self.args.base_path, uuid=self.args.destination
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/common.py", line 116, in get_biomedsheet_path
    raise CouldNotFindBioMedSheet(msg)
cubi_tk.snappy.common.CouldNotFindBioMedSheet: Could not find sample sheet for UUID /sodarZone/projects/3c/3cdefbd9-67b1-465e-937a-232ec1da47f8/landing_zones/blance@CHARITE/single_cell_lung_patients/lung_patients_whole_genome_sequencing/20210924_201211. Dataset configuration: All = {'sodar_uuid': '3cdefbd9-67b1-465e-937a-232ec1da47f8', 'file': 'Samplesheet.tsv', 'search_patterns': [{'left': '**/*_R1_001.fastq.gz', 'right': '**/*_R2_001.fastq.gz'}], 'search_paths': ['/fast/scratch/groups/cubi/blance_c/2021-06-25_Lung_Patients_WGS/incoming'], 'type': 'matched_cancer', 'naming_scheme': 'only_secondary_id'}
```
- Using the project's UUID as destination:
```
sak) [blance_c@med0624 pipeline]$ cubi-tk snappy itransfer-ngs-mapping --tsv-shortcut cancer --remote-dir-date 2021-09-30 3cdefbd9-67b1-465e-937a-232ec1da47f8
[I 211004 11:44:53] Starting cubi-tk snappy itransfer-ngs-mapping
[I 211004 11:44:53]   args: Namespace(base_path='/fast/work/groups/cubi/projects/2021-06-25_Lung_Patients_WGS/pipeline', cmd='snappy', config=None, destination='3cdefbd9-67b1-465e-937a-232ec1da47f8', first_batch=0, last_batch=None, mapper='bwa', num_parallel_transfers=8, remote_dir_date='2021-09-30', remote_dir_pattern='{library_name}/ngs_mapping/{date}', snappy_cmd=<bound method SnappyItransferCommandBase.run of <class 'cubi_tk.snappy.itransfer_ngs_mapping.SnappyItransferNgsMappingCommand'>>, sodar_api_token='37fca4c405664d8e298e7895c4726051b0772a825c656f8d641bb02e77f33502', sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', tsv_shortcut='cancer', validate_and_move=False, verbose=False, yes=False)
[I 211004 11:44:53] Will start at /fast/work/groups/cubi/projects/2021-06-25_Lung_Patients_WGS/pipeline
[I 211004 11:44:53] Libraries in sheet:
    p027-N1-DNA1-WGS1
    p027-T1-DNA1-WGS1
    p030-N1-DNA1-WGS1
    p030-T1-DNA1-WGS1
    p031-N1-DNA1-WGS1
    p031-T1-DNA1-WGS1
    p032-N1-DNA1-WGS1
    p032-T1-DNA1-WGS1
    p033-N1-DNA1-WGS1
    p033-T1-DNA1-WGS1
    p034-N1-DNA1-WGS1
    p034-T1-DNA1-WGS1
[I 211004 11:44:53] No active Landing Zone available for UUID 3cdefbd9-67b1-465e-937a-232ec1da47f8
Can the process create a new landing zone? [yN] y
[I 211004 11:45:00] Creating new Landing Zone...
[E 211004 11:45:00] Expected one assay, found 3
[I 211004 11:45:00] Try specifying an explicit --assay parameter
Traceback (most recent call last):
  File "/fast/work/users/blance_c/miniconda3/envs/sak/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/__init__.py", line 89, in run
    return args.snappy_cmd(args, parser, subparser)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 194, in run
    return cls(args).execute()
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 648, in execute
    lz_uuid, transfer_jobs = self.build_jobs(library_names)
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 317, in build_jobs
    lz_uuid, lz_irods_path = self.get_sodar_info()
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 468, in get_sodar_info
    project_uuid=in_destination
  File "/fast/work/users/blance_c/Development/saks/cubi-tk/cubi_tk/snappy/itransfer_common.py", line 539, in create_landing_zone
    project_uuid=project_uuid,
  File "/fast/work/users/blance_c/miniconda3/envs/sak/lib/python3.7/site-packages/sodar_cli/api/landingzone.py", line 58, in create
    raise Exception("Invalid number of assays in investigation!")  # TODO
Exception: Invalid number of assays in investigation!
```
- Used the project UUID as destination with the `--assay` option:
```
(sak) [blance_c@med0624 pipeline]$ cubi-tk snappy itransfer-ngs-mapping --tsv-shortcut cancer --remote-dir-date 2021-09-30 --assay 860ef3e8-5321-4c24-9c6d-44164a46db1d 3cdefbd9-67b1-465e-937a-232ec1da47f8
usage: cubi-tk [-h] [--verbose] [--version] [--config CONFIG]
               [--sodar-server-url SODAR_SERVER_URL]
               [--sodar-api-token SODAR_API_TOKEN]
               {isa-tpl,isa-tab,snappy,sodar,irods,org-raw,sea-snap,archive}
               ...
cubi-tk: error: unrecognized arguments: --assay 3cdefbd9-67b1-465e-937a-232ec1da47f8
```

**Possible fix**
1. Implement the `--assay` option for all `snappy` & `sodar` options. Compatible with `cubi-tk sodar pull-raw-data`, which has this option, or
2. Allow landing zone SODAR path as destination. Compatible with `cubi-tk sodar ingest-fastq`, which allows any landing zone path as destination.

The first option allows more checks: if `cubi-tk` knows about the project & assay, it can perform more health checks of the data (for example, upload only the files that are relevant for the assay, when the `ngs-mapping` step contains exome & transcriptome data).

The second option is more flexible, compatible with `cubi-tk sodar ingest-fastq` (also cluster to SODAR direction, unlike `cubi-tk sodar pull-raw-data`, which is the opposite, and therefore _requires_ the assay UUID). It is also problably easier to implement.

I'd like to start working on a fix asap, please let me know which option you think is the most suitable.

**Comment by eudesbarbosa** [comment]
@ericblanc20, in #54 we changed the way we call `cubi-tk snappy itransfer-ngs-mapping` to not depend on the path to the sample sheet, that means that the name of the file should be specified in the `config.yaml`.  
Does the file 'Samplesheet.tsv' exist in the `.snappy_pipeline` directory? If not, can you import the sample sheet from SODAR?

**Comment by ericblanc20** [comment]
Yes, the `Samplesheet.tsv` exists in the `.snappy_pipeline` directory.

The samplesheet is actually found, when the project UUID is given as destination (see third attempt above). Unfortunately, in that case, the correct assay isn't picked up, to existing landing zone isn't found, `cubi-tk` tries to create a new landing zone, but fails because there are multiple assays.

However, when the destination UUID is the landing zone's, then of course the samplesheet isn't found. 

I hope it makes sense.

**Comment by eudesbarbosa** [comment]
It does make sense, thanks for the long description of the problem.

Ideally both options should be available. Option *1* looks like a TODO that never really materialized, and *2* looks like a bug.
In short: whichever option you choose to implement would be welcome.
