### ISSUE TITLE
snappy pull-raw-data fails

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/cubi-tk#78]
**Describe the bug**

`cubit-tk snappy pull-raw-data` fails because `--allow-missing` is not passed to the underlying sodar command.

**To Reproduce**

```
$ cubi-tk snappy pull-raw-data --dry-run --assay a5a4ed8c-d0ab-4755-8e89-a0e23813bb50 --base-path . 7097920f-d1ce-4014-a4f0-97f2c2ef9b81
[I 211208 09:32:38] Will start at .
[I 211208 09:32:38] Loading configuration file and look for dataset
[I 211208 09:32:38] => will download to /fast/work/groups/cubi/projects/2021-10-01_TRCB/input_links
[I 211208 09:32:38] Using cubi-tk sodar pull-raw-data to actually download data
Traceback (most recent call last):
  File "/fast/work/users/blance_c/miniconda3/envs/sak_dev/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/fast/work/users/blance_c/Development/saks/devel/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/fast/work/users/blance_c/Development/saks/devel/cubi_tk/snappy/__init__.py", line 97, in run
    return args.snappy_cmd(args, parser, subparser)
  File "/fast/work/users/blance_c/Development/saks/devel/cubi_tk/snappy/pull_raw_data.py", line 121, in run
    return cls(Config(**args)).execute()
  File "/fast/work/users/blance_c/Development/saks/devel/cubi_tk/snappy/pull_raw_data.py", line 157, in execute
    sodar_pull_raw_data.Config(
TypeError: __init__() missing 1 required positional argument: 'allow_missing'
```

**Expected behavior**

No error & download files from SODAR.

**Comment by eudesbarbosa** [comment]
Related to #60
